"""
A list of human-readable names for the locations in Frogmonster.
"""

dash = "Dash"  # Marvin's Domain: Defeat Marvin
sticky_hands = "Sticky Hands"  # Outskirts: Sticky Hands
tongue_swing = "Tongue Swing"  # Forest Floor: Defeat Chroma
runi_key = "Runi Key"  # Well: Defeat Dekula
glowbug = "Glowbug"  # Found in Lost Swamp, Very Lost Swamp
frog = "Frog"  # Found in about a hundred locations
fly = "Fly"  # Found in Lost Swamp, Outskirts
dragonfly = "Dragonfly"  # CHECK: Lost Swamp
eel = "Eel"  # Found in Very Lost Swamp (May require dash or Frog?) CHECK: Lost Swamp
bass = "Bass"  # Found in Green Sea CHECK: Lost Swamp
blue_snack = "Blue Snack"  # Found in Marvin's Domain, Bins' Machine
purple_snack = "Purple Snack"  # Found in Marvin's Domain
magnet_roach = "Magnet Roach"  # Yellow Forest: Cromb's Shop 5 -- can you eat this somewhere?
mushroll = "Mushroll"  # Found in Marvin's Domain
mushfrog = "Mushfrog"  # Found in Marvin's Domain
beet = "Beet"  # Found in Outskirts
skater = "Skater"  # Found in Very Lost Swamp
soul_frog = "Soul Frog"  # Found anywhere you can die
river_fish = "River Fish"  # Found in Yellow Forest
bird = "Bird"  # Found in Yellow Forest
leafbug = "Leafbug"  # Found in Yellow Forest, also for sale
wormy = "Wormy"  # Found in Bins' Machine
minnow = "Minnow"  # Found in Yellow Forest (Town)
turtle = "Turtle"  # Found in Green Sea
blue_jelly = "Blue Jelly"  # Found in Green Sea -- Behind Key Door
roof_snail = "Roof Snail"  # Found in City
crab = "Crab" # Found in Lost Swamp, City, Undercity 
bridge_frog = "Bridge Frog"  # Found in City
cricket = "Cricket"  # Found in City
spider = "Spider"
moth = "Moth"
ammofly = "Ammofly"
pecker = "Pecker"
soul_fish = "Soul Fish"  # Found anywhere you can die. Also for sale in City
fog_fly = "Fog Fly"
cicada = "Cicada"
mantis = "Mantis"
jungle_snack = "Jungle Snack"
gecko = "Gecko"
bee = "Bee"
mushroom = "Mushroom"  # Found in Moridono's Domain
tang = "Tang"
axolotyl = "Axolotyl"
mite = "Mite"  # Found in Ridge
health_1 = "Health 1"  # Outskirts: Defeat The Long Beast
health_2 = "Health 2"  # Very Lost Swamp: Defeat Yanoy
health_3 = "Health 3"  # Hive: Defeat Foraz
health_4 = "Health 4"  # Yellow Forest: Cromb's Shop
health_5 = "Health 5"  # Yellow Forest: Cromb's Shop
health_6 = "Health 6"  # City: Save Newt from Thickness
mana_1 = "Mana 1"  # Yellow Forest: Defeat Limbs
mana_2 = "Mana 2"  # Thickness: Defeat Djumbo
mana_3 = "Mana 3"
mana_4 = "Mana 4"  # City: Wren's Shop 1
mana_5 = "Mana 5"  # City: Defeat Xoto
mana_6 = "Mana 6"  # City: Save Scoot from Treetops
reeder = "Reeder"  # Lost Swamp: Gift from Blue
machine_gun = "Munchinator"  # Marvin's Domain: Machine Gun
weepwood_bow = "Weepwood Bow"  # Very Lost Swamp: Defeat Supo
finisher = "Finisher"  # Yellow Forest: Gift from Finley
fire_fruit_juicer = "Fire Fruit Juicer"  # Old Road: Defeat Valda
gatling_gun = "Gatling Gun"  # Supo's Gatling Gun
wooden_cannon = "Wooden Cannon"  # Fog Garden: Defeat Hedgeward
fireball = "Fireball"  # Lost Swamp: Fireball
mushbomb = "Mushbomb"  # Marvin's Domain: Mushbomb
sharp_shot = "Sharp Shot"  # Outskirts: Sharp Shot
beans = "Beans"  # Yellow Forest: Cromb's Shop
zap = "Zap"  # Green Sea: Zap (Requires Key)
slam = "Slam"  # Fog Garden: Slam (Requires Key)
hive = "Hive"  # City: Save Shoot from Hive
puff = "Puff"  # Treetops: Puff (Requires Key)
bug_slot_1 = "Bug Slot 1"  # Yellow Forest: Defeat Placeholder
bug_slot_2 = "Bug Slot 2"  # Lost Swamp: Defeat Groth
bug_slot_3 = "Bug Slot 3"  # City: Wren's Shop (Requires 10 Bugs)
bug_slot_4 = "Bug Slot 4"  # City: Wren's Shop (Requires 20 Bugs)
bug_slot_5 = "Bug Slot 5"  # City: Wren's Shop (Requires 30 Bugs)
bug_slot_6 = "Bug Slot 6"  # City: Wren's Shop (Requires 40 Bugs)
bug_slot_7 = "Bug Slot 7"  # Cicada Cove: Defeat Tymbal
metal_ore_1 = "Metal Ore 1"  # Lost Swamp: Blue's Shack 
metal_ore_2 = "Metal Ore 2"  # Marvin's Domain: Hidden Alcove near Mushfrog Pond
metal_ore_3 = "Metal Ore 3"  # Very Lost Swamp: Pillar Arena
metal_ore_4 = "Metal Ore 4"  # Yellow Forest: Cromb's Shop
metal_ore_5 = "Metal Ore 5"  # Under City Platforming (TESTING - Requires Dash?)
metal_ore_6 = "Metal Ore 6"  # Old Road: In Between Arenas
metal_ore_7 = "Metal Ore 7"  # Well: Tenth Floor
metal_ore_8 = "Metal Ore 8"  # City: Save Boot from Really Lost Swamp
metal_ore_9 = "Metal Ore 9"  # Fog Garden: Chest Behind Key
metal_ore_10 = "Metal Ore 10"  # Forest Floor: Swinging Above Toro Arena
metal_ore_11 = "Metal Ore 11"  # Cicada Cove: In the Red Ferns
metal_ore_12 = "Metal Ore 12"  # Under Under City - Next to Save Point (Requires Fire)
metal_ore_13 = "Metal Ore 13"  # Moridono's Domain: Before Boss
metal_ore_14 = "Metal Ore 14"  # Quarry: Invisible Chest
metal_ore_15 = "Metal Ore 15"  # Drywood: After Zythida
metal_ore_16 = "Metal Ore 16"  # Deep: Outside Krogar
metal_ore_17 = "Metal Ore 17"  # Outskirts: Defeat Borp
metal_ore_18 = "Metal Ore 18"  # Forest Floor: Defeat Mud
metal_ore_19 = "Metal Ore 19"  # Old Road: Defeat Balsam
eel_trophy = "Eel Trophy"  # Green Sea: Defeat Bog and Chog
eye_fragment = "Eye Fragment"  # Ridge: Behind the 6-Eye Door
key_1 = "Key 1"  # Yellow Forest: Cromb's Shop
key_2 = "Key 2"  # City: Wren's Shop
key_3 = "Key 3"  # Somewhere near Fog Garden I think (TESTING - Where?)
smooth_stone_1 = "Smooth Stone 1"  # Lost Swamp: Underwater After Groth
smooth_stone_2 = "Smooth Stone 2"  # Lost Swamp: Near Fireball
smooth_stone_3 = "Smooth Stone 3"  # Marvin's Domain: Poison Cloud Arena Lower Level
smooth_stone_4 = "Smooth Stone 4"  # Outskirts: In The Long Beast's Lair
smooth_stone_5 = "Smooth Stone 5"  # Green Sea: Underwater Webs
smooth_stone_6 = "Smooth Stone 6"  # Old Road: Near First Save
smooth_stone_7 = "Smooth Stone 7"  # Well (Testing - Where?) PROBABLY DOESN'T EXIST
smooth_stone_8 = "Smooth Stone 8"  # Forest Floor: At the Top of the Climbing Trees near City
smooth_stone_9 = "Smooth Stone 9"  # Under Under City: Upper Floor
smooth_stone_10 = "Smooth Stone 10"  # Reef (Testing - Where?)
smooth_stone_11 = "Smooth Stone 11"  # Moridono's Domain: Before First Arena 
smooth_stone_12 = "Smooth Stone 12"  # Rootden: Before the Branching Path
square_rock_1 = "Square Rock 1"  # Yellow Forest: In the Bamboo by Marvin Entrance
square_rock_2 = "Square Rock 2"  # Outskirts: After Second Arena
square_rock_3 = "Square Rock 3"  # Green Sea: Chest Behind Key
square_rock_4 = "Square Rock 4"  # Old Wood: After Jumper Arena
square_rock_5 = "Square Rock 5"  # Hive: Next to Tongue Swing Area
square_rock_6 = "Square Rock 6"  # City: Behind Boxes in the Old House 
square_rock_7 = "Square Rock 7"  # Treetops: Chest Behind Key
square_rock_8 = "Square Rock 8"  # Temple: Invisible Chest after Door Crab
square_rock_9 = "Square Rock 9"  # Deep: In Chomper Arena
square_rock_10 = "Square Rock 10"  # Estate: Behind Breakable Wall
dark_pebble_1 = "Dark Pebble 1"  # Marvin's Domain: Inside a Mushroom Tree
dark_pebble_2 = "Dark Pebble 2"  # Yellow Forest: Above Very Lost Swamp Entrance
dark_pebble_3 = "Dark Pebble 3"  # Thickness: Before Djumbo
dark_pebble_4 = "Dark Pebble 4"  # City: Gift from Blue
dark_pebble_5 = "Dark Pebble 5"  # Under City: Behind Webs
dark_pebble_6 = "Dark Pebble 6"  # Moridono's Domain: In Clearing Near Drills
dark_pebble_7 = "Dark Pebble 7"  # City: Behind Breakable Door
dark_pebble_8 = "Dark Pebble 8"  # Under Under City: Barge Arena Platforming Challenge
sparkling_gem_1 = "Sparkling Gem 1"  # Marvin's Domain: Poison Cloud Arena Upper Level
sparkling_gem_2 = "Sparkling Gem 2"  # Yellow Forest: Above Chrom
sparkling_gem_3 = "Sparkling Gem 3"  # Well: Fourth Floor
sparkling_gem_4 = "Sparkling Gem 4"  # City: Gift from Supa
sparkling_gem_5 = "Sparkling Gem 5"  # Temple: Closed-Off Chest
sparkling_gem_6 = "Sparkling Gem 6"  # Estate: Under the Pool
seedling_myzand_upgrade = "Seedling Myzand Upgrade"  # Ridge: Defeat Runi
reeder_myzand_upgrade = "Reeder Myzand Upgrade"  # Under Under City: Defeat Barge
machine_gun_myzand_upgrade = "Munchinator Myzand Upgrade"  # Moridono's Domain: Defeat Moridono
weepwood_bow_myzand_upgrade = "Weepwood Bow Myzand Upgrade"  # Reef: Defeat Krogar & The Scavengers
finisher_myzand_upgrade = "Finisher Myzand Upgrade"  # Temple: Defeat Door Crab
fire_fruit_juicer_myzand_upgrade = "Fire Fruit Juicer Myzand Upgrade"  # Ridge: Defeat Oosk and Dord
gatling_gun_myzand_upgrade = "Gatling Gun Myzand Upgrade"  # Rootden: Defeat Zythida
wooden_cannon_myzand_upgrade = "Wooden Cannon Myzand Upgrade"  # Temple: Defeat Lazaro
yellow_forest_puzzle = "Yellow Forest Puzzle"  # Yellow Forest: Puzzle in the Town
city_puzzle_1 = "City Puzzle 1"  # City: Puzzle behind the Torches
city_puzzle_2 = "City Puzzle 2"  # City: Puzzle in the Boxes House
mansion_puzzle_1 = "Mansion Puzzle 1" # Estate: Right Puzzle
mansion_puzzle_2 = "Mansion Puzzle 2" # Estate: Left Puzzle
fog_garden_puzzle_1 = "Fog Garden Puzzle 1"  # Fog Garden: Left Puzzle
fog_garden_puzzle_2 = "Fog Garden Puzzle 2"  # Fog Garden: Right Puzzle
coin_chest_1 = "Lost Swamp: After Blue"
coin_chest_2 = "Yellow Forest: River"
coin_chest_3 = "Thickness: Hug the Left Wall"
coin_chest_4 = "Well: Eighth Floor"
coin_chest_5 = "Well: First Floor"
coin_chest_6 = "Very Lost Swamp: Outskirts Entrance"

goal = "Defeat Myzand"
workshop_access = "Can Use Workshop"