from .names import item_names as i

every_bug_without_mushroom = [  # Bug names paired with their effect IDs (NOT Item IDs), to be used by client if Shuffle Bug-Eating Effects is on.
    (1,  i.glowbug),
    (2,  i.frog),
    (3,  i.fly),
    (4,  i.dragonfly),
    (5,  i.eel),
    (6,  i.bass),
    (7,  i.blue_snack),
    (8,  i.purple_snack),
    (9,  i.magnet_roach),
    (10, i.mushroll),
    (11, i.mushfrog),
    (12, i.beet),
    (13, i.skater),
    (14, i.soul_frog),
    (15, i.river_fish),
    (16, i.bird),
    (17, i.leafbug),
    (18, i.wormy),
    (19, i.minnow),
    (20, i.turtle),
    (21, i.blue_jelly),
    (22, i.roof_snail),
    (23, i.crab),
    (24, i.bridge_frog),
    (25, i.cricket),
    (26, i.spider),
    (27, i.moth),
    (28, i.ammofly),
    (29, i.pecker),
    (30, i.soul_fish),
    (31, i.fog_fly),
    (32, i.cicada),
    (33, i.mantis),
    (34, i.jungle_snack),
    (35, i.gecko),
    (37, i.bee),
    (38, i.tang),
    (39, i.axolotyl),
    (40, i.mite)
]

every_bug = every_bug_without_mushroom + [(36, i.mushroom)]  # there's currently a magic number for this in fill_slot_data so be sure to change that if you need to change this.