from typing import Dict, NamedTuple, List

from .names import region_names as r

class FrogmonsterRegionData(NamedTuple):
    connecting_regions: List[str] = []

region_data_table: Dict[str, FrogmonsterRegionData] = {
r.lost_swamp: FrogmonsterRegionData(),
r.marvins: FrogmonsterRegionData(),
r.outskirts: FrogmonsterRegionData(),
r.very_lost_swamp: FrogmonsterRegionData(),
r.yellow_forest: FrogmonsterRegionData(),
r.yellow_forest_town: FrogmonsterRegionData(),
r.yellow_forest_side: FrogmonsterRegionData(),
r.limbs_arena: FrogmonsterRegionData(),
r.green_sea: FrogmonsterRegionData(),
r.green_sea_before: FrogmonsterRegionData(),
r.green_sea_after: FrogmonsterRegionData(),
r.green_sea_key: FrogmonsterRegionData(),
r.city: FrogmonsterRegionData(),
r.workshop: FrogmonsterRegionData(),
r.old_road: FrogmonsterRegionData(),
r.old_wood: FrogmonsterRegionData(),
r.thickness: FrogmonsterRegionData(),
r.well: FrogmonsterRegionData(),
r.estate: FrogmonsterRegionData(),
r.fog_garden: FrogmonsterRegionData(),
r.fog_garden_key: FrogmonsterRegionData(),
r.under_city: FrogmonsterRegionData(),
r.forest_floor: FrogmonsterRegionData(),
r.treetops: FrogmonsterRegionData(),
r.treetops_key: FrogmonsterRegionData(),
r.cicada_cove: FrogmonsterRegionData(),
r.hive: FrogmonsterRegionData(),
r.runi_arena: FrogmonsterRegionData(),
r.ridge: FrogmonsterRegionData(),
r.moridonos: FrogmonsterRegionData(),
r.moridono_arena: FrogmonsterRegionData(),
r.reef: FrogmonsterRegionData(),
r.deep: FrogmonsterRegionData(),
r.krogar_arena: FrogmonsterRegionData(),
r.drywood: FrogmonsterRegionData(),
r.rootden: FrogmonsterRegionData(),
r.temple: FrogmonsterRegionData(),
r.temple_top: FrogmonsterRegionData(),
r.quarry: FrogmonsterRegionData(),
r.under_under_city: FrogmonsterRegionData(),
r.barge_arena: FrogmonsterRegionData(),
r.under_under_city_lower: FrogmonsterRegionData(),
r.myzand: FrogmonsterRegionData(),

r.anywhere: FrogmonsterRegionData(),
r.bug: FrogmonsterRegionData(),
 }