# location names to be referenced in Locations.py

# ---- Pellys ----
standard_pelly = "Standard Pelly"
glass_pelly = "Glass Pelly"
gold_pelly = "Gold Pelly"

# ---- Shop Items ----
upgrade_pur = "Upgrade Purchase"

# ---- Valuables ----
# -- All --
diamond = "Diamond Valuable"
ring = "Emerald Ring Valuable"
goblet = "Goblet Valuable"
ocarina = "Ocarina Valuable"
pocket_watch = "Pocket Watch Valuable"
uranium_mug = "Uranium Mug Valuable"
crown = "Crown Valuable"
doll = "Doll Valuable"
frog_toy = "Wind-Up Frog Valuable"
gem_box = "Gem Box Valuable"
globe = "Globe Valuable"
money = "Money Valuable"
monkey = "Toy Monkey Valuable"
uranium_plate = "Uranium Plate Valuable"
small_vase = "Small Vase Valuable"
champagne = "Champagne Bottle Valuable"
clown_doll = "Clown Doll Valuable"
trophy = "Trophy Valuable"
vase = "Vase Valuable"
large_vase = "Large Vase Valuable"
animal_crate = "Animal Crate Valuable"
bonsai = "Bonsai Tree Valuable"

# -- Heaman Manor --
music_box = "Music Box Valuable"
gramophone = "Gramophone Valuable"
rhino = "Rhino Box Valuable"
scream_doll = "Scream Doll Valuable"
grand_piano = "Grand Piano Valuable"
harp = "Harp Valuable"
painting = "Painting Valuable"
grandfather_clock = "Grandfather Clock Valuable"
dinosaur_skeleton = "Dinosaur Skeleton Valuable"
golden_statue = "Golden Statue Valuable"
tv = "Television Valuable"
radio = "Radio Valuable"
ship_in_a_bottle = "Ship In A Bottle Valuable"

# -- McJannek Station --
desktop_computer = "Desktop Computer Valuable"
fan = "Fan Valuable"
explosive_barrel = "Explosive Barrel Valuable"
sample = "Sample Valuable"
big_sample = "Big Sample Valuable"
flamethrower = "Flamethrower Valuable"
science_station = "Science Station Valuable"
server = "Server Valuable"
printer = "3D Printer Valuable"
hdd = "Hard Disk Drive Valuable"
ice_saw = "Ice Saw Valuable"
laptop = "Laptop Valuable"
propane = "Propane Tank Valuable"
sample_pack = "Sample Six Pack Valuable"
guitar = "Guitar Valuable"
sample_cooler = "Sample Cooler Valuable"
leg_ice = "Leg Ice Block Valuable"
skeleton_ice = "Skeleton Ice Block Valuable"

# -- Swiftbroom Academy --
chomp_book = "Chomp Book Valuable"
love_potion = "Love Potion Valuable"
cube_of_knowledge = "Cube Of Knowledge Valuable"
staff = "Dumgolf's Staff Valuable"
large_sword = "Large Sword Valuable"
broom = "Wizard Broom Valuable"
hourglass = "Hourglass Valuable"
master_potion = "Master Potion Valuable"
goblin_head = "Goblin Head Statue Valuable"
griffin = "Griffin Statue Valuable"
power_crystal = "Power Crystal Valuable"


# ---- Monsters ----
animal_soul = "Animal Soul" 
duck_soul = "Apex Predator Soul" 
bowtie_soul = "Bowtie Soul" 
chef_soul = "Chef Soul" 
clown_soul = "Clown Soul" 
headman_soul = "Headman Soul" 
hidden_soul = "Hidden Soul" 
huntsman_soul = "Huntsman Soul" 
mentalist_soul = "Mentalist Soul" 
reaper_soul = "Reaper Soul" 
robe_soul = "Robe Soul" 
rugrat_soul = "Rugrat Soul"
shadow_child_soul = "Shadow Child Soul"
spewer_soul = "Spewer Soul"
trudge_soul = "Trudge Soul" 
upscream_soul= "Upscream Soul"